name: Deploy PreTeXt Site to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy-pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: oscarlevin/pretext:small

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt --break-system-packages

      - name: Build site
        run: pretext build --deploys

      - name: Stage site
        run: pretext deploy --stage-only

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/stage

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
